---

- name: establish package
  become: "{{ (ansible_system == 'Linux') | bool }}"
  package:
    name: git
    state: present
  tags: install

- name: establish dependencies enforced by settings
  become: "{{ (ansible_system == 'Linux') | bool }}"
  package:
    name: "{{ lookup('template', './tools_list.j2') | unique }}"
    state: present
  failed_when: false
  tags: install

- name: global .gitignore
  when:
    - git_global_gitignore is defined
    - git_global_gitignore | length > 0
  block:
    - name: setup global gitignore path
      set_fact:
        git_configuration:
          "{{ {
               'core': {
                 'excludesfile': '%s/.gitignore_global' | format(ansible_env.HOME),
               },
             } | combine(git_configuration, recursive=True) }}"

    - name: ensure global gitignore path presence
      file:
        path: "{{ git_configuration['core']['excludesfile'] | dirname }}"
        state: directory

    - name: establish global gitignore file
      lineinfile:
        line: "{{ item }}"
        path: "{{ git_configuration['core']['excludesfile'] }}"
        mode: "u=rwx,go=rx"
        create: true
      loop: "{{ git_global_gitignore }}"
  tags: configure

- name: establish configuration
  git_config:
    name: "{{ item['setting'] }}"
    scope: "{{ git_scope }}"
    value: "{{ item['value'] }}"
  loop: "{{ lookup('template', './settings_with_keys_collapsed_to_path.j2') }}"
  tags: configure
