---

- name: establish 'git' package
  become: yes
  package: 
    name: git
    state: latest

- name: establish dependencies enforced by settings
  become: yes
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ used_tools }}"
 
- name: set up global .gitignore
  copy:
    src: .gitignore_global
    dest: ~/.gitignore_global    
    owner: "{{ ansible_user }}"
    mode: "u=rwx,go=rx"

- name: configure git settings
  git_config:
    name: "{{ item.setting }}"
    scope: "{{ scope }}"
    value: "{{ item.value  }}"
  with_items: "{{ collapsed_settings }}"

- name: establish bash completion
  get_url:
    url: "https://github.com/git/git/blob/master/contrib/completion/git-completion.bash"
    dest: "{{ '/etc/bash_completion.d/ ' if ansible_system == 'Linux' else '/opt/local/etc/bash_completion.d/' }}"
    mode: "u=rwx,go="
    owner: "{{ ansible_user }}"
  when:
    - ansible_system == 'Linux' or ansible_system == 'Darwin'
