---

- name: establish package
  become: yes
  package: 
    name: git 
    state: latest
  tags: install

- name: establish dependencies enforced by settings
  become: yes
  package:
    name: "{{ lookup('template', './tools_list.j2') | unique }}"
    state: present
  tags: install
 
- name: establish global .gitignore
  when: global_gitignore is defined 
  lineinfile:
    line: "{{ item }}"
    path: "{{ lookup('env','HOME') }}/.gitignore_global" 
    owner: "{{ ansible_user }}"
    mode: "u=rwx,go=rx"
    create: yes
  loop: "{{ global_gitignore }}"
  tags: configure

- name: establish configuration
  git_config:
    name: "{{ item['setting']}}"
    scope: "{{ scope }}"
    value: "{{ item['value'] }}"
  loop: "{{ lookup('template', './settings_with_keys_collapsed_to_path.j2') }}"
  tags: configure

