---

- name: establish package
  become: true
  package:
    name: git
    state: present
  tags: install

- name: establish dependencies enforced by settings
  become: true
  package:
    name: "{{ lookup('template', './tools_list.j2') | unique }}"
    state: present
  tags: install

- name: establish global .gitignore
  when: global_gitignore is defined
  become: false
  lineinfile:
    line: "{{ item }}"
    path: "{{ configuration['core']['excludesfile'] | default(lookup('env','HOME') + '/.gitignore_global') }}"
    mode: "u=rwx,go=rx"
    create: true
  loop: "{{ global_gitignore }}"
  tags: configure

- name: establish configuration
  git_config:
    name: "{{ item['setting'] }}"
    scope: "{{ scope }}"
    value: "{{ item['value'] }}"
  loop: "{{ lookup('template', './settings_with_keys_collapsed_to_path.j2') }}"
  tags: configure
