---

- name: Converge
  hosts: all
  roles:
    - role: git
      vars:
        git_scope: global
        git_configuration:
          user:
            name: "Name Surname"
            email: "name@surname.com"
          core:
            excludesfile: "/tmp/gitignore"

  post_tasks:
    - name: check 'git' presence
      block:
        - name: attempt to use 'git' command
          command: 'git --version'
          changed_when: false
          register: r
        - name: evaluate command presence
          assert:
            that:
              - r.rc == 0
            fail_msg: "'git' command should be installed"
